# ==== scalpx_config.yaml ====

LIVE_MODE: true
MIN_SCORE: 8.0
WATCHLIST:
  - AAPL
  - AMD
  - TSLA
  - NVDA
  - SPY

DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1393834483098320947/D7NxdLvH1gVq90woLwpofrmo6xGHdXknAwpFYrvGbc8cs4TQ5ogGXP048KWOWKeLKy5C"

EMAIL:
  SENDER: "llamaguyai@gmail.com"
  PASSWORD: "abwe wgoh hxln lphe"
  RECEIVER: "llamaguyai@gmail.com"

SMS_NUMBER: "+17174437727"

DAILY_REPORT_BAT: "C:\\Users\\Jamal Lawrence\\Documents\\ScalpX\\scalpx_report_launcher.bat"
